Allow access to Spring Boot Healthcheck
CDCgov/prime-data-input-client pull request #206
Opened 2020-12-01 21:17 UTC by nickrobison-usds

Added a GET exception to the SecurityConfiguration, which will allow anonymous access to the overall healthcheck API.

The Gateway can now issue a `GET` request to `/actuator/health` and get a response.

By default, this doesn't expose any internal details on the nested checks, just a simple UP/DOWN status.

Looking at the internal [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-health) Ben linked to, I think it's acceptable to obscure the internal information and simply return UP/DOWN as the health check. In the future, we could expand this to be more detailed, but I think I'd rather move that to a private admin port which we don't route to the world, rather than relying on our auth implementation.

2020-12-01 21:39 UTC, benwarfield-usds requested changes
There's a custom RequestMatcher for the actuator endpoints—a little more robust if we use that.

2020-12-01 21:39 UTC, benwarfield-usds commented on backend/src/main/java/gov/cdc/usds/simplereport/config/SecurityConfiguration.java
> +				.antMatchers(HttpMethod.GET, "/actuator/health").permitAll()
Should use the `EndpointMatcher` so it stays working if somebody decides to move it to `/management` in the future. (Also should probably use the same indentation mechanism that the code around it uses, though editor style continues to be a thing we don't have a consistent approach to.)

2020-12-01 21:39 UTC, benwarfield-usds commented on backend/src/main/java/gov/cdc/usds/simplereport/config/SecurityConfiguration.java
> +        String EMAIL = "email";
I would prefer to discuss why I do this than just get into edit wars where we make stylistic changes to each other's code all the time. 😁

2020-12-02 16:29 UTC, emmanuel-apau approved these changes
LGTM

2020-12-02 20:39 UTC, benwarfield-usds approved these changes
:shipit: 

We should probably tweak our actuator settings as well, but that's not urgent.

2020-12-02 20:50 UTC, merged